version: "3.4"

services:
  database:
    container_name: database-p1-e86fab91-30aa-44a2-8f02-b7d53a8fee90
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env
    ports:
      - "5433:5433"

  flyway:
    image: flyway/flyway:8.4.0-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
